title: raspberry-pi-fix-noobs
hero_image: images/banner.png
description: raspberry-pi-fix-noobs description
version: 4
listed: false
copyedit: false
last_tested: "2020-01-29"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
