title: Break and Fix Your Raspbian Installation with NOOBS
hero_image: images/banner.png
description: Learn how to recover a working installation of Raspbian when something goes wrong. 
version: 4
listed: false
copyedit: false
last_tested: "2020-01-29"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
